#pragma kernel CSMain

// RWStructuredBuffer<float3> positions;
// RWStructuredBuffer<float2> velocities;

struct Agent
{
    float3 position;
    float2 velocity;
};

RWStructuredBuffer<Agent> agents;
RWStructuredBuffer<float2> flockCenter;
RWStructuredBuffer<float2> flockAlignment;
RWStructuredBuffer<float2> flockSeparation;

StructuredBuffer<float> terrainHeight;

cbuffer DeltaTimeBuffer
{
    float DeltaTime[1];
}

cbuffer AgentsCountBuffer
{
    int AgentsCount[1];
}

cbuffer MaxDistanceBuffer
{
    float MaxDistance[1];
}

cbuffer MinDistanceBuffer
{
    float MinDistance[1];
}

cbuffer SpeedBuffer
{
    float Speed[1];
}

cbuffer CohesionWeightBuffer
{
    float CohesionWeight[1];
}

cbuffer AlignmentWeightBuffer
{
    float AlignmentWeight[1];
}

cbuffer SeparationWeightBuffer
{
    float SeparationWeight[1];
}

cbuffer TerrainOffsetXBuffer
{
    float TerrainOffsetX[1];
}

cbuffer TerrainOffsetZBuffer
{
    float TerrainOffsetZ[1];
}

RWStructuredBuffer<int> debugNumber;
RWStructuredBuffer<float2> debugFloat2;
RWStructuredBuffer<float3> debugFloat3;

[numthreads(32,1,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    const int agents_count = AgentsCount[0];
    const int index = id.x;

    int nearby_count = 0;
    float2 center = float2(0, 0);
    float2 alignment = float2(0, 0);
    float2 separation = float2(0, 0);

    Agent agent = agents[index];

    for (int i = 0; i < agents_count; i++)
    {
        const Agent other = agents[i];
        const float2 offset = other.position.xz - agent.position.xz;
        const float square_distance = offset.x * offset.x + offset.y * offset.y;
        if (square_distance > MaxDistance[0]) continue;
        nearby_count++;
        center += offset;
        alignment += other.velocity;
        if (i == index) continue;
        separation -= offset * (1.0 / square_distance - 1.0 / MaxDistance[0]);
    }

    const float average = 1.0f / nearby_count;
    center *= average;
    alignment *= average;


    center *= CohesionWeight[0];
    if (nearby_count > 1) center = normalize(center);
    alignment *= AlignmentWeight[0];
    separation *= SeparationWeight[0];

    if (index == 0) debugFloat2[0] = center;

    flockCenter[index] = center;
    flockAlignment[index] = alignment;
    flockSeparation[index] = separation;

    if (length(center) < 1)
    {
        center = float2(0, 0);
    }

    float2 acceleration = center + alignment + separation;

    agent.velocity += acceleration;
    agent.velocity = lerp(normalize(agent.velocity), agent.velocity, 0.1f);
    
    float3 velocity3 = float3(agent.velocity.x, 0, agent.velocity.y);

    agent.position += velocity3 * (Speed[0] * DeltaTime[0]);

    agents[index] = agent;
}
