#pragma kernel CSMain

// RWStructuredBuffer<float3> positions;
// RWStructuredBuffer<float2> velocities;

struct Agent
{
    float3 position;
    float2 velocity;
};

RWStructuredBuffer<Agent> agents;
RWStructuredBuffer<float2> flockCenter;
RWStructuredBuffer<float2> flockAlignment;
RWStructuredBuffer<float2> flockSeparation;

StructuredBuffer<float> terrainHeight;

cbuffer DeltaTimeBuffer
{
    float DeltaTime[1];
}

cbuffer AgentsCountBuffer
{
    int AgentsCount[1];
}

cbuffer MaxDistanceBuffer
{
    float MaxDistance[1];
}

cbuffer MinDistanceBuffer
{
    float MinDistance[1];
}

cbuffer SpeedBuffer
{
    float Speed[1];
}

cbuffer CohesionWeightBuffer
{
    float CohesionWeight[1];
}

cbuffer AlignmentWeightBuffer
{
    float AlignmentWeight[1];
}

cbuffer SeparationWeightBuffer
{
    float SeparationWeight[1];
}

cbuffer TerrainOffsetXBuffer
{
    float TerrainOffsetX[1];
}

cbuffer TerrainOffsetZBuffer
{
    float TerrainOffsetZ[1];
}



RWStructuredBuffer<int> debugNumber;
RWStructuredBuffer<float2> debugFloat2;
RWStructuredBuffer<float3> debugFloat3;

[numthreads(32,1,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    int agentsCount = AgentsCount[0];
    int index = id.x;

    int nearbyCount = 0;
    int separationCount = 0;
    flockCenter[index] = float2(0, 0);
    flockAlignment[index] = float2(0, 0);

    for (int i = 0; i < agentsCount; i++)
    {
        float2 offset = agents[i].position.xz - agents[index].position.xz;
        float squareDistance = offset.x * offset.x + offset.y * offset.y;
        if (squareDistance > MaxDistance[0]) continue;
        nearbyCount++;
        flockCenter[index] += offset;
        if (length(agents[i].velocity) != 0) flockAlignment[index] += normalize(agents[i].velocity);

        float distance = sqrt(squareDistance);
        if (distance > MinDistance[0] || i == index) continue;
        separationCount++;
        flockSeparation[index] -= offset / squareDistance;
    }

    if (nearbyCount > 0)
    {
        flockCenter[index] /= nearbyCount;
        flockAlignment[index] /= nearbyCount;

        flockCenter[index] *= CohesionWeight[0];
        flockAlignment[index] *= AlignmentWeight[0];
        flockSeparation[index] *= SeparationWeight[0];

        float cohesion = length(flockCenter[index]);
        if (cohesion < 1)// || cohesion > 10)
        {
            flockCenter[index] = float2(0, 0);
        }

        float2 acceleration = flockCenter[index] + flockAlignment[index] + flockSeparation[index];

        agents[index].velocity += acceleration;
        agents[index].velocity *= 0.95f;
        float3 velocity3 = float3(agents[index].velocity.x, 0, agents[index].velocity.y);

        
        agents[index].position += velocity3 * (Speed[0] * DeltaTime[0]);
    }
    else
    {
        flockCenter[index] = agents[index].position.xz;
        flockAlignment[index] = agents[index].velocity;
        flockSeparation[index] = float2(0, 0);
    }
    if (separationCount == 0) 
    {
        flockSeparation[index] = float2(0, 0);
    }
    
    // const int resolution = 33;
    // float2 clampedPosition = clamp(positions[index].xz, float2(-15, -15), float2(15, 15));
    // if (index == 0) debugFloat2[0] = clampedPosition;
    // float2 terrainPosition = clampedPosition - float2(TerrainOffsetX[0], TerrainOffsetZ[0]);
    // float fractionX = terrainPosition.x * resolution / 30.0f;
    // float fractionZ = terrainPosition.y * resolution / 30.0f;
    // int positionIndex = int(fractionX + fractionZ * resolution);
    // // if(index == 0) debugNumber[0] = positionIndex;
    // if (positionIndex < 0 || positionIndex >= resolution * resolution)
    // {
    //     return;
    // }
    // float terrainHeightValue = terrainHeight[positionIndex];
    // // if(index == 0) debugNumber[0] = terrainHeightValue;
    // positions[index].y = terrainHeightValue;
    // if (index == 0) debugFloat3[0] = positions[0];
}
