#pragma kernel CSMain

RWTexture2D<float4> Result;
cbuffer MousePositionBuffer
{
    float2 MousePosition[1];
};

cbuffer TimeBuffer
{
    float Time[1];
};

[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float x_norm = id.x / 64.0f;
    float y_norm = id.y / 64.0f;

    float2 norm = float2(x_norm, y_norm);
    float2 xy = MousePosition[0] - norm;

    float timeSin = (sin(Time[0] * 5) + 1.0f) * 0.1f;
    float distance = length(xy) * 7;

    float value = 1.0f - distance + timeSin;
    float alpha = clamp(value, 0.0f, 1.0f);
    
    Result[id.xy] = float4(value,value,value,1.0 - alpha);
}